[build]
dockerfile = "./x86_64-unknown-linux-gnu.dockerfile"
#pre-build = [
#    "dpkg --add-architecture $CROSS_DEB_ARCH",
#    "apt-get update && apt-get install -y --no-install-recommends libssl-dev:$CROSS_DEB_ARCH",
#    "rm /usr/lib/x86_64-linux-gnu/libssl.so*",
#    "rm /usr/lib/x86_64-linux-gnu/libcrypto.so*",
#]
#
#[build.env]
#passthrough = ["OPENSSL_STATIC=1"]
